# The packages required to set up our desired libvirt environment.
libvirt_packages:
  - qemu-kvm
  - libvirt
  - libvirt-python
  - libguestfs-tools
  - python-lxml
  - polkit-pkla-compat

# The (Debian) packages required to set up our desired libvirt environment.
libvirt_packages_debian:
  - qemu-kvm
  - libvirt-clients
  - python-libvirt
  - libguestfs-tools
  - python-lxml

# The name of the libvirt service.
libvirtd_service: libvirtd

# If running in chroot-like environments (containers)
chrooted: false
